# Rest Client (VS Code Extension - HTTP Requests)
@server=http://localhost:3000


### Listar salas disponíveis
GET {{server}}/solicitacoes/salas

### Listar todas as solicitações
GET {{server}}/solicitacoes

### Criar solicitação de sala
POST {{server}}/solicitacoes
Content-Type: application/json

{
  "sala": "SALA 1",
  "data": "2026-05-01",
  "hora": "14:00",
  "finalidade": "Reunião de projeto"
}

### Buscar uma solicitação por chave
GET {{server}}/solicitacoes/1/2026-05-01/14:00

### Atualizar status de uma solicitação
PUT {{server}}/solicitacoes/1/2026-05-01/14:00
Content-Type: application/json

{
  "status": "Aprovado"
}

### Deletar uma solicitação
DELETE {{server}}/solicitacoes/1/2026-05-01/14:00